name: ParaEssentials
main: moe.stuff.para.ParaEssentials
version: 1.0
api-version: 1.12

commands:
  help:
    description: Prints a nice help message.
    usage: /<command>
    permission: para.command.help
  ignore:
    description: Ignore another player in chat.
    usage: /<command> <player>
    permission: para.command.ignore
  ignorelist:
    description: Retreive ignored players.
    usage: /<command>
    permission: para.command.ignorelist
    aliases: [il]
  msg:
    description: Message another player.
    usage: /<command> <player> <message>
    permission: para.command.msg
    aliases: [message, m]
  r:
    description: Reply to the last /msg.
    usage: /<command> <message>
    permission: para.command.r
    aliases: [reply]
  togglechat:
    description: Toggles chat.
    usage: /<command>
    permission: para.command.togglechat
  toggledeathmsgs:
    description: Toggles death messages.
    usage: /<command>
    permission: para.command.toggledeathmsgs
    aliases: [toggledeathmessages]
  kill:
    description: Kill yourself (or if you're a server operator, others too).
    usage: /<command> [target | target1... targetN]
    permission: para.command.kill
